### ISSUE TITLE
Have you test YaHS on low coverage hic data?

### ISSUE THREAD

**Issue by xiekunwhy** [c-zhou/yahs#1]
Hi,

My effective hic coverage is very low (~80X raw data, but only ~8X after merging step of Arima Genomics' mapping pipeline), do you have any suggestions to scaffold contigs using such low depth hic data?

Best,
Kun

**Comment by c-zhou** [comment]
Hello Kun,

Thanks very much for your enquiry.

No, we have not yet tested it with such low depth hic data. I am very interested to see how the scaffolding result will look like.

In your case, the problem is why such a large fraction of hic reads were filtered out. What comes to my mind is either because the reads did not map or the genome is highly repetitive which leads to many multi-mappings. I do not think we can do much for the first case - there must be something wrong. For the second case, the Arima Genomics' mapping pipeline has a default filtering threshold for mapping qualities, which I think is 10. You can try to turn the filter off and see how it looks like. However, YaHS has not been tested with multi-mappings either - actually I doubt if any hic scaffolding tools have. You can give it a try though.

It would be very helpful to diagnose the problem if you can visualise the hic signals - both in contig level and scaffold level. There are a plethora of hic visualisation tools out there. I added a demo to the repo which uses Juicebox. You can give it a try as well.

Best,
Chenxi

**Comment by xiekunwhy** [comment]
Hi Chenxi,

Maybe you are right, but when I use all mapped data, YaHS is very aggressive, and collapse difference chromosomes sequence into one longer scaffold, and the long scaffold number is much smaller than real chromosomes number.

I found that YaHS is much more aggressive than other tools like salsa2 and pins(https://github.com/dfguan/pin_hic), and generate smaller long scaffold number than real chromosomes number oftenly when I use it anchor some other species, are there some parameters to avoid these?

Best,
Kun

**Comment by c-zhou** [comment]
Hi Kun, 

Just to let you know that we have introduced some new strategies for dealing with background mapping noises.

Best,
Chenxi
