### ISSUE TITLE
What is RAM limit?

### ISSUE THREAD

**Issue by xiekunwhy** [c-zhou/yahs#18]
Hi,
Yahs told the RAM limit is too low, what is RAM limit, and how to change this limit?
[I::run_yahs] RAM total: 125.555GB
[I::run_yahs] RAM limit: 0.421GB

[I::print_asm_stats] assembly stats:
[I::print_asm_stats]  N50: 136225 (n = 770)
[I::print_asm_stats]  N90: 23879 (n = 5328)
[I::run_yahs] scaffolding round 1 resolution = 5000
[I::run_scaffolding] starting norm estimation...
[I::run_scaffolding] No enough memory. Try higher resolutions... End of scaffolding round.
[I::run_scaffolding] RAM    limit: 0.391GB
[I::run_scaffolding] RAM required: 11.514GB

Best,
Kun

**Comment by c-zhou** [comment]
Hi Kun,

RAM limit suggests the memory available for running yahs. In your case, you should have a 128Gb machine, however, only 0.4Gb memory was available - either because the memory was occupied by other programs or your system has a user limit. For the latter case, `ulimit -a` will give you some clues.

Best,
Chenxi

**Comment by xiekunwhy** [comment]
Ok, I see.

And I found that YaHS is not a good scaffolding tools when N50 is short (<1Mb?), any plan to make some improvements? Or do you know some tools which suitable for such case?

Best,
Kun

**Comment by c-zhou** [comment]
I guess you are talking about what I mentioned in [#17](https://github.com/c-zhou/yahs/issues/17#issuecomment-1141524583). What I mean was that HiC data is intrinsically not good for scaffolding highly fragmented assemblies due to lack of resolution. But in terms of how fragmented the assembly need to be to stop HiC scaffolding from working, it is very hard to say. We do have many assembles with N50 less than 500Kb scaffolded very well with HiC data and I will not be surprised to see it working for even more fragmented assemblies depending on the HiC libraries and depth of coverage etc. 

Best,
Chenxi

**Comment by skoren** [comment]
I also encountered this issue on the NIH cluster: https://hpc.nih.gov. It reported 250gb total and <1gb available even though I have >100gb reserved on the node:
```
[I::run_yahs] RAM total: 251.614GB
[I::run_yahs] RAM limit: 0.648GB
```
and doesn't do any scaffolding since it can't fit into the limit. It doesn't report errors, just does no scaffolding, it'd probably be better to fail in these cases.

I'm not sure why it's reporting such a low limit as ulimit shows 100gb available (e.g. my reservation) and top/proc both show 70+gb free:
```
% ulimit -a
core file size          (blocks, -c) 1
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1029828
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) 104857600
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

% cat /proc/meminfo
MemTotal:       263836448 kB
MemFree:        74984732 kB
MemAvailable:   248743812 kB
Buffers:          156640 kB

% top
KiB Mem : 26383644+total, 69761680 free, 14685360 used, 17938940+buff/cache
KiB Swap:  2097148 total,  2049532 free,    47616 used. 24798489+avail Mem 
```

**Comment by c-zhou** [comment]
Hi Sergey,

I am not sure what the problem was. I am thinking if it is due to something specific to the SLURM cluster configuration. `RAM limit` is supposed to be the memory available at runtime (see code below). I am wondering what was the peak memory consumption during the run. It should be reported at the end of the log file. If you could share the entire log file, I can probably dig a little further.

> It doesn't report errors, just does no scaffolding, it'd probably be better to fail in these cases.

In the latest commit, I added the `--no-mem-check` option which will disable the runtime memory check. The program will be terminated immediately with memory allocation failures. I also tagged [v1.2a.1](https://github.com/c-zhou/yahs/tree/v1.2a.1) to include this commit.

https://github.com/c-zhou/yahs/blob/857b0613fc36c41d1c0b271b4809552e7de534bc/asset.c#L109-L116

Best,
Chenxi

**Comment by skoren** [comment]
Thanks, I was able to run by modifying the code to pull the SLURM env variable (if present) to get the memory limit since mem free on the node doesn't really matter in that case, it's how much has been reserved:
```
--- a/asset.c
+++ b/asset.c
@@ -29,6 +29,7 @@
  *********************************************************************************/
 #include <string.h>
 #include <stdio.h>
+#include <stdlib.h>
 #include <assert.h>
 #include <unistd.h>
 #include <sys/resource.h>
@@ -106,6 +107,11 @@ long physmem_total(void)

 long physmem_avail(void)
 {
+   const char * val = getenv( "SLURM_MEM_PER_NODE" );
+   if (val != NULL) {
+      return atol(val)*1024*1024;
+   }
+
     #if defined _SC_AVPHYS_PAGES && defined _SC_PAGESIZE
     {
         /* This works on linux-gnu, solaris2 and cygwin */
```

The total memory used is about 30gb.

**Comment by c-zhou** [comment]
Thanks Sergey. Yeah, I think SLURM's memory management is different.

Chenxi
