### ISSUE TITLE
Problem with juicer pre when making hic file

### ISSUE THREAD

**Issue by athenasyarifa** [c-zhou/yahs#24]
Hi @c-zhou 
Thank you for making a great tool! I did the scaffolding, but I am having problems when I try to make the hic file, specifically when running this script: 

`(juicer pre yahs.out.bin yahs.out_scaffolds_final.agp yahs.out_scaffolds_final.fa.fai | sort -k2,2d -k6,6d -T ./ --parallel=8 -S32G | awk 'NF' > alignments_sorted.txt.part) && (mv alignments_sorted.txt.part alignments_sorted.txt)`

Failed to run and only generated empty alignment_sorted.txt. Below is what was written in the output file: 

`[E::make_asm_dict_from_agp] sequence ptg000164l not found`

Can you help me? Thanks in advance!

Cheers, 
Rifa

**Comment by c-zhou** [comment]
Hello Rifa,

Thanks for using YaHS. `juicer pre` expects to see the FASTA index file for the original contig file instead of the scaffold file, i.e., you need to change `yahs.out_scaffolds_final.fa.fai` to `${contigs}.fai`.

Best,
Chenxi

**Comment by athenasyarifa** [comment]
Ah yes, I'm sorry I missed that. Thank you so much!

**Comment by Duda5** [comment]
Hi @c-zhou,

I am re-opening this issue because I got sort of a similar error.
Scaffolding finished successfully and my directory contains the following files (+ `bam` file that I used as input for `yahs` command, `contigs.fa` and `contigs.fa.fai`)
```
pol_asm_bwa_filt_merged_sl_noDUP.bam
pol_asm_bwa_filt_merged_sl_noDUP.bam.bai
pol_asm_YaHS.bin
pol_asm_YaHS_inital_break_01.agp
pol_asm_YaHS_inital_break_02.agp
pol_asm_YaHS_inital_break_03.agp
pol_asm_YaHS_inital_break_04.agp
pol_asm_YaHS_r01.agp
pol_asm_YaHS_r01_break.agp
pol_asm_YaHS_r02.agp
pol_asm_YaHS_r02_break.agp
pol_asm_YaHS_r03.agp
pol_asm_YaHS_r03_break.agp
pol_asm_YaHS_r04.agp
pol_asm_YaHS_r04_break.agp
pol_asm_YaHS_r05.agp
pol_asm_YaHS_r05_break.agp
pol_asm_YaHS_r06.agp
pol_asm_YaHS_r06_break.agp
pol_asm_YaHS_r07.agp
pol_asm_YaHS_r07_break.agp
pol_asm_YaHS_r08.agp
pol_asm_YaHS_r08_break.agp
pol_asm_YaHS_r09.agp
pol_asm_YaHS_r09_break.agp
pol_asm_YaHS_r10.agp
pol_asm_YaHS_r10_break.agp
pol_asm_YaHS_scaffolds_final.agp
pol_asm_YaHS_scaffolds_final.fa
contigs.fa
contigs.fa.fai
```

When I try to run this command:
`$(juicer pre pol_asm_YaHS.bin pol_asm_YaHS_scaffolds_final.agp contigs.fa.fai 2>juicer_pre.log | sort -k2,2d -k6,6d -T ./ --parallel=8 -S32G | awk 'NF' > alignments_sorted.txt.part) && (mv alignments_sorted.txt.part alignments_sorted.txt)`
I get this error in log file:
`[E::make_asm_dict_from_agp] sequence  not found`
It does not specify what is not found (there are 2 spaces) and I am not sure what is causing it as all required input files are in the same directory.

`.fai` file was generated with `samtools faidx contigs.fa`
`juicer` version is 1.1

When I run just this part of the command - `juicer pre pol_asm_YaHS.bin pol_asm_YaHS_scaffolds_final.agp contigs.fa.fai 2>juicer_pre.log`, the error in the log is the same, but I am also getting `Segmentation fault (core dumped)` to stdout.

Would be grateful for your help!

**Comment by Duda5** [comment]
**Update:** I think my `pol_asm_YaHS_scaffolds_final.agp` file was corrupted. I figured it out from the large difference in size between it and other `.agp` files in the output direcotry.

I repeated scaffolding and was able to run `juicer pre` successfully!
