### ISSUE TITLE
Program halted sequence number exceeds limit

### ISSUE THREAD

**Issue by papelypluma** [c-zhou/yahs#7]
Hi yahs developers. I'd like to seek for your help if there's a way to address this issue that I've encountered. 

> [I::run_yahs] RAM total: 251.789GB
> [I::run_yahs] RAM limit: 133.369GB
> [I::contig_error_break] dist threshold for contig error break: 1000000
> [I::contig_error_break] performed 5 round assembly error correction. Made 502 breaks
> [E::run_yahs] sequence number exceeds limit (54720 > 45000)
> [E::run_yahs] consider removing short sequences before scaffolding, or
> [E::run_yahs] running without error correction (--no-contig-ec) if due to excessive contig error breaks
> [E::run_yahs] program halted...

I'm not sure if it's due to the inherent RAM limit that caused the program to stop.

Thank you for your help!

**Comment by c-zhou** [comment]
Hello papelypluma,
 
Thanks for using YaHS. This is because the number of contigs in your assembly exceeds the limits. YaHS need to do a pairwise matching of contigs. 54720 contigs will end up with an untractable large number. I am not sure how your assembly looks like, are there many short contigs? If so, I would suggest filtering out those short ones before running the program, maybe those <50Kb and they tend to introduce scaffolding errors anyway. You can generate a new FASTA file without those short contigs. You do not need to redo the alignment. The old BED/BAM file is OK. Do NOT reuse the intermediate BIN file.

If you do not mind rebuilding the program, I have updated the code to introduce a new parameter `-l` which will do the trick, so you can stick to the original FASTA file. But still, you need to start from the BED or BAM file.

Best,
Chenxi

**Comment by papelypluma** [comment]
Hi Chenxi, thank you for the help! I re-ran the tool with less contigs, and it worked.
